# fly.toml app configuration file generated for turso-leak on 2023-11-21T13:10:12-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "turso-leak"
primary_region = "sea"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
